name: Firebase Deploy

on:
  push:
    branches:
      - main  # Triggers on push to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Set up Google Cloud credentials
      # Use the secret in the environment variable
      run: echo "${{ secrets.FIREBASE_ADMINSDK_JSON }}" > /tmp/credentials.json

    - name: Authenticate with Firebase
      run: gcloud auth activate-service-account --key-file=/tmp/credentials.json

    - name: Deploy to Firebase
      run: firebase deploy --only hosting
      env:
        GOOGLE_APPLICATION_CREDENTIALS: /tmp/credentials.json
